#+TITLE: MHC cookbook
#+AUTHOR: Yoshinari Nomura
#+EMAIL:
#+DATE:
#+OPTIONS: H:3 num:2 toc:nil
#+OPTIONS: ^:nil @:t \n:nil ::t |:t f:t TeX:t
#+OPTIONS: skip:nil
#+OPTIONS: author:t
#+OPTIONS: email:nil
#+OPTIONS: creator:nil
#+OPTIONS: timestamp:nil
#+OPTIONS: timestamps:nil
#+OPTIONS: d:nil
#+OPTIONS: tags:t
#+TEXT:
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE: ja
#+STARTUP: odd
#+LATEX_CLASS: jsarticle
#+LATEX_CLASS_OPTIONS: [a4j,dvipdfmx]
# #+LATEX_HEADER: \usepackage{plain-article}
# #+LATEX_HEADER: \renewcommand\maketitle{}
# #+LATEX_HEADER: \pagestyle{empty}
# #+LaTeX: \thispagestyle{empty}

* FullCalendar viewer for mhc

  In [[file:full-calendar][full-calendar]] directory:

  1) Prepare JSON data with =mhc scan=
     [[file:full-calendar/update-json.sh][update-json.sh]]:
     #+BEGIN_SRC shell-script
       #!/bin/sh

       mhc scan thismonth+6m  --search='category:holiday'   \
                              --format=json > holidays.json
       mhc scan thismonth+6m  --search='!category:holiday'  \
                              --format=json > events.json
     #+END_SRC

  2) open =full-calendar.html= with a browser

* Forecasting next occurrence of a recurring event
  Heron is an event forecaster https://github.com/nomlab/heron

  #+BEGIN_SRC shell-script
    mhc scan all --search='subject:"Group meeting"' | awk '{print $1}' | heron forecast
    2015-08-17

    mhc scan all --search='recurrence_tag:"HairCut"' | awk '{print $1}' | heron forecast
    2015-10-10
  #+END_SRC

* Show last-year's schedule at the left buffer.
  Sometimes, you may want to check the last year's schedule on browsing
  future schedule. This code would help you.

  Split window horizontally and show two mhc-summary-buffers, then
  the left buffer follows the right one.

  #+BEGIN_SRC emacs-lisp
    (defun mhc-summary-get-left-summary-window ()
      "Return the left mhc-summary buffer of current buffer."
      (save-window-excursion
        (let* ((left-win (window-in-direction 'left))
               (left-buf (window-buffer left-win)))
          (if (and left-win
                   (eq (with-current-buffer left-buf major-mode)
                       'mhc-summary-mode))
              left-win
            nil))))

    (defun mhc-summary-set-left-window ()
      (let ((left-win (mhc-summary-get-left-summary-window))
            (last-year (mhc-date-yy- (mhc-summary-current-date-month) 1)))
        (if left-win
            (with-selected-window left-win
              (mhc-goto-month last-year)))))

    (add-hook 'mhc-summary-mode-hook 'mhc-summary-set-left-window)
  #+END_SRC

  How to use it:
  1) Show the mhc-summary-buffer of current month by =M-x mhc=.
  2) Split horizontally by =C-x 3=.
     Yes, you may see the current month in both buffers.
  3) Set focus at the right-side one.
  4) Now, moving the month in the right buffer,
     left buffer follows showing the previous year of the right buffer.
